sudo: required

services:
    - docker

before_install:
    - docker build -t shivamyth/dockeryoutube -f Dockerfile.dev . 

script:
    - docker run -e CI=true -it shivamyth/dockeryoutube npm run test


deploy:
    provider: elasticbeanstalk
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    region: "ap-south-1"
    app: "docker-youtube"
    env: "DockerYoutube-env"
    bucket_name: "elasticbeanstalk-ap-south-1-062642699343"
    bucket_path: "docker-youtube"
    on:
        branch: master